### ISSUE TITLE
Support passing a list of fingerprint templates to the `MATCH` function

### ISSUE THREAD

**Issue by tobiasmcnulty** [LSHTM-ORK/ODK_Biometrics#18]
If possible, we would like to support a workflow in our forms where we can pass more than one fingerprint template to the MATCH function and get back the ordered list of match scores for each template.

In our form, we would then use the [max()](https://docs.getodk.org/form-operators-functions/#max) function to decide based on the highest score whether or not the captured template matches one of the stored templates.

One thing I'm not sure about is whether the list of scores received from Keppel could be stored in a single variable in the XLS form / ODK Central (eventually). Is this possible? Or would they need to be split out into separate variables?

For the multi-value return from Keppel, we would expect back (a) the list of match scores (plural), and (b) the captured fingerprint template (singular).

If receiving a list of match scores in the form will be difficult or impossible, we could foreseeably get back only the highest score (and the fingerprint template in the multi-value option), and then we would still be able to reproduce the match scores on the server if ever needed for auditing purposes.

**Comment by seadowg** [comment]
@tobiasmcnulty what sort of flow would the form your envisioning have? I'dl like to get a sense of the problem being solved here.

**Comment by tobiasmcnulty** [comment]
> @tobiasmcnulty what sort of flow would the form your envisioning have? I'dl like to get a sense of the problem being solved here.

The problem solved is to avoid a false negative when the the original fingerprint captures were swapped (i.e., "right" is stored as "left" and "left" as "right" in our database) due to operator error. Below is an excerpt of what this step in the flow might look like. Specifically, "option 2" proceeds to "scan other thumb" instead of "scan left thumb."

<img width="638" alt="Screenshot 2024-05-23 at 11 57 27 AM" src="https://github.com/LSHTM-ORK/ODK_Biometrics/assets/160132/98ca3208-8ff9-447b-bb46-221b1bedb8e4">

**Comment by seadowg** [comment]
> The problem solved is to avoid a false negative when the the original fingerprint captures were swapped (i.e., "right" is stored as "left" and "left" as "right" in our database) due to operator error.

> In our form, we would then use the [max()](https://docs.getodk.org/form-operators-functions/#max) function to decide based on the highest score whether or not the captured template matches one of the stored templates.

Interesting! I guess then you could theoretically have both thumbs in the existing data and then just have one "match" question where you scan either to verify the person (assuming the match score is tuned high enough in the form) where you scan either. I guess this approach is already possible, it just requires multiple scans followed by the `max()` logic?

> One thing I'm not sure about is whether the list of scores received from Keppel could be stored in a single variable in the XLS form / ODK Central (eventually). Is this possible? Or would they need to be split out into separate variables?

I guess it could work in a way where you return the multiple match scores as a single string and then use string splitting to pull it apart in the form. However, it feels like the form logic could be lighter if the action [returned multiple values to a group](https://docs.getodk.org/collect-external-apps/#external-apps-to-populate-multiple-fields). I could imagine that the input is something like this (in the group's `body::intent`):

```
uk.ac.lshtm.keppel.android.MULTI_MATCH(uk.ac.lshtm.keppel.android.iso_template_1=/data/finger_1,uk.ac.lshtm.keppel.android.iso_template_2=/data/finger_2, uk.ac.lshtm.keppel.android.return_score_1="my_score_1", uk.ac.lshtm.keppel.android.return_score_2="my_score_2")
```

The scores would then be returned into `my_score_1` and `my_score_2` fields. An alternative approach here would be to pass the templates in as a single joined string (with a known separator), but I don't think that's better given we end up needing a convention for the return values anyway.

One risk I see here is running into problems with size limits on passing data around in Android - [anything over a 1MB will explode](https://developer.android.com/guide/components/activities/parcelables-and-bundles). I believe (and please correct me if I'm wrong) that an ISO template is not at risk of that (as it's generally a few hundred bytes), but obviosuly allowing multiple to be passed in would make this possible.

**Comment by seadowg** [comment]
After discussing this with @tobiasmcnulty again, it appears that there isn't really a use for all the scores to be returned - the best one is good enough. The flow we're supporting here is using a single finger to identify a person based on multiple templates, so returning the max score and then checking that against a suitably high threshold will mean simpler forms and less visual noise than my original proposal of returning multiple scores.

The updated action would like this (in the `appearance` of a question):

```
uk.ac.lshtm.keppel.android.MULTI_MATCH(uk.ac.lshtm.keppel.android.iso_template_1=/data/finger_1,uk.ac.lshtm.keppel.android.iso_template_2=/data/finger_2)
```

This would then return a single result to the question of which would be the highest score obtained from matching a scanned finger against `iso_template_1`, `iso_template_2` (and so on).
