### ISSUE TITLE
"Please place finger on scanner" never goes away, but scanner light turns off

### ISSUE THREAD

**Issue by tobiasmcnulty** [LSHTM-ORK/ODK_Biometrics#42]
This is similar to #22 but happens after the scan appears to be successful.

We see "START!" in the logs:

https://github.com/LSHTM-ORK/ODK_Biometrics/blob/102a09e92130cf48108984485378b1c36d07d2a5/Android/biomini/src/main/java/uk/ac/lshtm/keppel/biomini/BioMiniScanner.kt#L265-L281

But nothing from Keppel after that, and "Please place finger on scanner" continues spinning on the screen.

Might there be a way to implement a backup timeout if the call to the SDK library never returns? The cancel button works fine and we don't need to use the power off/on workflow to recover, but it does reoccur from time to time.

#22 is also still happening on some tablets from time to time.

**Comment by copelco** [comment]
Logcat output:

[BioRugged-BW10RS-Android-13_2024-11-01_134106.logcat.zip](https://github.com/user-attachments/files/17603185/BioRugged-BW10RS-Android-13_2024-11-01_134106.logcat.zip)
