### ISSUE TITLE
Return hash with score

### ISSUE THREAD

**Issue by chrissyhroberts** [LSHTM-ORK/ODK_Biometrics#44]
Just flagging this to @seadowg after discussion in ODK Insiders meeting 2024-11-06

For post-hoc verification and governance, I think it will be **essential** to return the hash when verifying a print via Keppel. 

i.e.

* Person is registered with fingerprints A, B and C
* Person scans finger B, which matches template for B
* Keppel returns score to variable ’score'
* Keppel returns hash to variable ‘template_test'

There’s a significant threat of dataset being vulnerable to tampering either on server or after download. 
For any official or regulated purposes like clinical trials or voting, there’d be no way to verify the scores without the hash. 

I can’t actually think of any use-case where the hash isn’t either desirable, or essential, so maybe a good idea to make it the only option to return both data points

**Comment by seadowg** [comment]
Do you mean the scanned ISO template that was used to match against the input templates? If so, that's already possible: https://github.com/LSHTM-ORK/ODK_Biometrics/blob/master/ACTIONS.md#multiple-field-example-2.

**Comment by chrissyhroberts** [comment]
Yep that’s what I meant! Hadn’t seen the actions.md file. Very useful. 

Thanks @seadowg
