### ISSUE TITLE
Returning template AND NFIQ via body::intent is cryptic or non-functional

### ISSUE THREAD

**Issue by chrissyhroberts** [LSHTM-ORK/ODK_Biometrics#47]
[keppel_body_intent_test.xlsx](https://github.com/user-attachments/files/17706865/keppel_body_intent_test.xlsx)

* The attached example form _should_ access both template and NFIQ through the group `body::intent` and return data to two fields. Scanning takes place as normal and scanner light goes off, but nothing is returned to the group variables. I think this is a bug, or a lack of clarity in the documentation. 

`uk.ac.lshtm.keppel.android.SCAN(uk.ac.lshtm.keppel.android.return_iso_template=my_iso_template_field, uk.ac.lshtm.keppel.android.return_nfiq=my_nfiq_field)` should send data within the group to `my_iso_template_field` and `my_nfiq_field` but no data is stored. 

* Also noted that ACTIONS.md says to use `body::intent` should start with `ex:uk.ac.lshtm.` when I don’t think the `ex:` is needed

**Comment by chrissyhroberts** [comment]
This problem appears to be with the documentation for ACTIONS.md

[keppel_basic.xlsx](https://github.com/user-attachments/files/17717018/keppel_basic.xlsx)
This form fixes most of the issues, but I can’t figure out how to get the score back from `return_score` when `body::intent` is used. 

The score is reported properly by both single and multi match when used as `ex:` intent through appearance, but so far can’t figure out why it doesn’t work when you specify i.e. `uk.ac.lshtm.keppel.android.return_score="validate_score”` in body::intent.

Will be an easy fix to docs once the score is being returned properly.

**Comment by seadowg** [comment]
> This problem appears to be with the documentation for ACTIONS.md

It looks to me like the problem was that the return field names weren't quoted. Is that correct?

> This form fixes most of the issues, but I can’t figure out how to get the score back from return_score when body::intent is used.

I gave this a quick try, and it looks like it's because you have `validate_score` using type `integer` rather than `decimal`. I'll add a note to the docs about that as well.
